import os

print("\nInstalling git... \n")
os.system("sudo apt install git")
print("Cloning Robots4Hospitals repo... \n")
os.system("git clone https://github.com/ap8718/Robots4Hospitals.git")
print("Changing directory to Robots4Hospitals/FinalCode/Tensorflow... \n")
os.chdir("Robots4Hospitals/FinalCode/Tensorflow")
print("Cloning Tensorflow/models repo... \n")
os.system("git clone https://github.com/tensorflow/models.git")
print("Changing directory to models/research... \n")
os.chdir("models/research")
print("Making protoc... \n")
os.system("protoc object_detection/protos/*.proto --python_out=.")
print("Cloning COCOAPI dataset... \n")
os.system("git clone https://github.com/cocodataset/cocoapi.git")
print("Changing directory to cocoapi/PythonAPI... \n")
os.chdir("cocoapi/PythonAPI")
print("Making COCOAPI... \n")
os.system("make")
print("Copying Pycocotools to Tensorflow/models/research... \n")
os.system("cp -r pycocotools ../../.")
print("Changing directory to Tensorflow/models/research... \n")
os.chdir("../..")
print("Copying TF Object Detection setup script... \n")
os.system("cp object_detection/packages/tf2/setup.py .")
print("Installing TF Object Detection API... \n")
os.system("python3 -m pip install .")
print("Changing directory to Robots4Hospitals/FinalCode... \n")
os.chdir("~/Robots4Hospitals/FinalCode/")
os.system("sudo apt install nano")
